In [1]:
import pandas as pd
tabela = pd.read_csv("clientes.csv") #importando a base de dados
display(tabela)

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,alto_gasto_pagamento_baixos,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,baixo_gasto_pagamento_alto,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,baixo_gasto_pagamento_medio,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,baixo_gasto_pagamento_baixo,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,alto_gasto_pagamento_medio,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,alto_gasto_pagamento_alto,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,alto_gasto_pagamento_medio,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,alto_gasto_pagamento_alto,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,baixo_gasto_pagamento_alto,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,alto_gasto_pagamento_medio,393.673696,Poor,1,0,0,0,1

In [2]:
#verfificar se tem valores vazios ou valores errados
print(tabela.info())
print(tabela.columns)

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  str
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  str
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  str
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  str
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), str(4)
memory usage: 19.1 MB
None
Index(['id_cliente', 'mes', 'idade', 'profissao', 'salario_anual',
       'num_contas', 'num_cartoes', 'juros_emprestimo', 'num_emprestimos',
       'dias_atraso', 'num_pagamentos_atrasados', 'num_verificacoes_credito',
       'mix_credito', 'divida_total', 'taxa_uso_credito',
       'idade_historico_credito', 'investimento_mensal',
       'comportamento_pagamento', 'saldo_final_mes', 'score_credito',
       'emprestimo_carro', 'emprestimo_casa', 'emprestimo_pessoal',
       'emprestimo_credito', 'emprestimo_estudantil'],
      dtype='str')

In [3]:
from sklearn.preprocessing import LabelEncoder

#vai transformar os textos em números da coluna específica
codificador_profissao = LabelEncoder()
tabela["profissao"] = codificador_profissao.fit_transform(tabela["profissao"])#o novo valor da coluna "profissao" é igual ao seu valor transformado em int com a ajuda do aplicador ".fit_transform"

codificador_mix_credito = LabelEncoder()
tabela["mix_credito"] = codificador_mix_credito.fit_transform(tabela["mix_credito"])

codificador_comportamento = LabelEncoder()
tabela["comportamento_pagamento"] = codificador_comportamento.fit_transform(tabela["comportamento_pagamento"])

In [4]:
#vamos escolher quais colunas vamos usar para treinar o modelo
#y é a coluna que vamos prever(a coluna"score_credito")
#x é a coluna que vamos usar para prever o score de crédito, não vamos usar a coluna id_cliente porque ela é um número qualquer e não ajuda na previsão
y = tabela["score_credito"]
x = tabela.drop(["score_credito", "id_cliente"], axis=1)#estou excluindo essas duas colunas usando o .drop(), e o axis=1 significa que eu estou escolhendo a coluna, e não a linha(linha: axis = 0).

from sklearn.model_selection import train_test_split

#separamos os dados em treino e teste, treino vamos dar para os modelos aprederem e teste vamos usar para ver se o modelo aprendeu corretamente
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=1)
#test_size=0.3 siginifca que 30% dos dados oferecidos seram usados como teste.
#e o random_state=1, sigifica que sempre que eu rodar esse código o resultado vai ser aleatório.

In [5]:
#modelo de árvore de decisão
from sklearn.ensemble import RandomForestClassifier
#modelo de vizinhos mais próximos
from sklearn.neighbors import KNeighborsClassifier

modelo_arvore = RandomForestClassifier()
modelo_knn = KNeighborsClassifier()

#treinando os modelos
modelo_arvore.fit(x_treino, y_treino)
modelo_knn.fit(x_treino, y_treino)

#se ele chutasse tudo "Standard", qual seria seu nível de acerto?
contagem_scores = tabela["score_credito"].value_counts()
print(contagem_scores["Standard"] / sum(contagem_scores))

0.53174

In [6]:
from sklearn.metrics import accuracy_score

#testamos os dois modelos
previsao_arvore = modelo_arvore.predict(x_teste)
previsao_knn = modelo_knn.predict(x_teste)

#comparamos o resultado com  o y_teste
display(accuracy_score(y_teste, previsao_arvore))
display(accuracy_score(y_teste, previsao_knn))

#como melhorar o modelo:
#GridSearch
#ter mais dados
#treinar outros parâmetros

0.8264

0.7324

In [7]:
#quais as características mais importantes para definir o score de crédito?
coluna = list(x_teste.columns)
importancia = pd.DataFrame(index=coluna, data=modelo_arvore.feature_importances_)
importancia = importancia * 100
print(importancia)

                                  0
mes                        3.987773
idade                      4.254425
profissao                  3.278066
salario_anual              5.107419
num_contas                 3.466982
num_cartoes                4.513067
juros_emprestimo           7.954790
num_emprestimos            3.055390
dias_atraso                6.564562
num_pagamentos_atrasados   4.538778
num_verificacoes_credito   4.271046
mix_credito                8.511006
divida_total              11.734676
taxa_uso_credito           5.059013
idade_historico_credito    7.617763
investimento_mensal        4.841587
comportamento_pagamento    2.352811
saldo_final_mes            5.413758
emprestimo_carro           0.689072
emprestimo_casa            0.710626
emprestimo_pessoal         0.684510
emprestimo_credito         0.698176
emprestimo_estudantil      0.694705

In [8]:
#agora vamos testar o modelo de árvore de decisão nesse novos clientes
#importar os novos clientes
novos_clientes = pd.read_csv("novos_clientes.csv")

#transformar os dados em str para números inteiros
#agora é so "transform", porque ja tem rotulos de int criados anteriormente e também porque iria sobreescrever os int ja criados
novos_clientes["profissao"] = codificador_profissao.transform(novos_clientes["profissao"])

novos_clientes["mix_credito"] = codificador_mix_credito.transform(novos_clientes["mix_credito"])

novos_clientes["comportamento_pagamento"] = codificador_comportamento.transform(novos_clientes["comportamento_pagamento"])

#fazer a previsão com o modelo escolhido
previsao = modelo_arvore.predict(novos_clientes)
display(novos_clientes)
display(previsao)

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,5,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,4,312.487689,1,1,0,0,0
1,4,32.0,0,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,5,300.994163,0,0,0,0,1
2,2,48.0,5,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,3,345.081577,0,1,0,1,0

array(['Poor', 'Standard', 'Standard'], dtype=object)